# Generated by Django 3.2.13 on 2024-03-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_completed']},
        ),
    ]
